-- Generated by gen_table_model.py. Do not edit by hand.
-- One rule is emitted for each non-empty CSV cell; blank cells have no rule.

type
  CCState: enum {
    C_I, C_ISD, C_IMAD, C_IMA, C_S, C_SXA, C_SMAD, C_SMA, C_M, C_MXA, C_E, C_EXA, C_MIA, C_EIA, C_SIA, C_IIA, C_IXD, C_X, C_XWB
  };
  DirState: enum {
    D_I, D_S, D_E, D_M, D_SD
  };

var
  cc_state: CCState;
  dir_state: DirState;

startstate "table roots"
begin
  cc_state := C_I;
  dir_state := D_I;
endstartstate;

  rule "CC I x Load"
    cc_state = C_I
  ==>
  begin
    cc_state := C_ISD;
  endrule;

  rule "CC I x SPMCP_fetch (coherent)"
    cc_state = C_I
  ==>
  begin
    cc_state := C_IXD;
  endrule;

  rule "CC I x SPMWB_store"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC I x Store"
    cc_state = C_I
  ==>
  begin
    cc_state := C_IMAD;
  endrule;

  rule "CC I x SPMWB_read (SPM)"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC I x SPMLD (SPM)"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC I x SPMST (SPM)"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Load"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMCP_fetch (coherent)"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMCP_install (SPM)"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMWB_store"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Store"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMWB_read (SPM)"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMLD (SPM)"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMST (SPM)"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Replacement"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Inv"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Exclusive Data 
from Dir"
    cc_state = C_ISD
  ==>
  begin
    cc_state := C_E;
  endrule;

  rule "CC IS^D x Data from Dir
(ack=0)"
    cc_state = C_ISD
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC IS^D x Data from 
Owner"
    cc_state = C_ISD
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC IM^AD x Load"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMCP_fetch (coherent)"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMCP_install (SPM)"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMWB_store"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Store"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMWB_read (SPM)"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMLD (SPM)"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMST (SPM)"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Replacement"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Fwd-GetS"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Fwd-GetM"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Data from Dir
(ack=0)"
    cc_state = C_IMAD
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC IM^AD x Data from Dir 
(ack>0)"
    cc_state = C_IMAD
  ==>
  begin
    cc_state := C_IMA;
  endrule;

  rule "CC IM^AD x Data from 
Owner"
    cc_state = C_IMAD
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC IM^AD x Inv-Ack"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Load"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMCP_fetch (coherent)"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMCP_install (SPM)"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMWB_store"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Store"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMWB_read (SPM)"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMLD (SPM)"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMST (SPM)"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Replacement"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Fwd-GetS"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Fwd-GetM"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Inv-Ack"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Last-Inv-Ack"
    cc_state = C_IMA
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC S x Load"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x SPMCP_fetch (coherent)"
    cc_state = C_S
  ==>
  begin
    cc_state := C_SXA;
  endrule;

  rule "CC S x SPMCP_install (SPM)"
    cc_state = C_S
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC S x SPMWB_store"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x Store"
    cc_state = C_S
  ==>
  begin
    cc_state := C_SMAD;
  endrule;

  rule "CC S x SPMWB_read (SPM)"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x SPMLD (SPM)"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x SPMST (SPM)"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x Replacement"
    cc_state = C_S
  ==>
  begin
    cc_state := C_SIA;
  endrule;

  rule "CC S x Inv"
    cc_state = C_S
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC SX^A x Load"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMCP_fetch (coherent)"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMCP_install (SPM)"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMWB_store"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Store"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMWB_read (SPM)"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMLD (SPM)"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMST (SPM)"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Replacement"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Fwd-GetS"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Fwd-GetM"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Inv"
    cc_state = C_SXA
  ==>
  begin
    cc_state := C_SXA;
  endrule;

  rule "CC SX^A x Put-Ack"
    cc_state = C_SXA
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC SM^AD x Load"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMCP_fetch (coherent)"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMCP_install (SPM)"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMWB_store"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Store"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMWB_read (SPM)"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMLD (SPM)"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMST (SPM)"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Replacement"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Fwd-GetS"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Fwd-GetM"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Inv"
    cc_state = C_SMAD
  ==>
  begin
    cc_state := C_IMAD;
  endrule;

  rule "CC SM^AD x Data from Dir
(ack=0)"
    cc_state = C_SMAD
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC SM^AD x Data from Dir 
(ack>0)"
    cc_state = C_SMAD
  ==>
  begin
    cc_state := C_SMA;
  endrule;

  rule "CC SM^AD x Inv-Ack"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Load"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMCP_fetch (coherent)"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMCP_install (SPM)"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMWB_store"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Store"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMWB_read (SPM)"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMLD (SPM)"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMST (SPM)"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Replacement"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Fwd-GetS"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Fwd-GetM"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Inv-Ack"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Last-Inv-Ack"
    cc_state = C_SMA
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC M x Load"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPMCP_fetch (coherent)"
    cc_state = C_M
  ==>
  begin
    cc_state := C_MXA;
  endrule;

  rule "CC M x SPMCP_install (SPM)"
    cc_state = C_M
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC M x SPMWB_store"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x Store"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPMWB_read (SPM)"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPMLD (SPM)"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPMST (SPM)"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x Replacement"
    cc_state = C_M
  ==>
  begin
    cc_state := C_MIA;
  endrule;

  rule "CC M x Fwd-GetS"
    cc_state = C_M
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC M x Fwd-GetM"
    cc_state = C_M
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC MX^A x Load"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMCP_fetch (coherent)"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMCP_install (SPM)"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMWB_store"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Store"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMWB_read (SPM)"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMLD (SPM)"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMST (SPM)"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Replacement"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Fwd-GetS"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Fwd-GetM"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Put-Ack"
    cc_state = C_MXA
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC E x Load"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x SPMCP_fetch (coherent)"
    cc_state = C_E
  ==>
  begin
    cc_state := C_EXA;
  endrule;

  rule "CC E x SPMCP_install (SPM)"
    cc_state = C_E
  ==>
  begin
    cc_state := C_E;
  endrule;

  rule "CC E x SPMWB_store"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x Store"
    cc_state = C_E
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC E x SPMWB_read (SPM)"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x SPMLD (SPM)"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x SPMST (SPM)"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x Replacement"
    cc_state = C_E
  ==>
  begin
    cc_state := C_EIA;
  endrule;

  rule "CC E x Fwd-GetS"
    cc_state = C_E
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC E x Fwd-GetM"
    cc_state = C_E
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC EX^A x Load"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMCP_fetch (coherent)"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMCP_install (SPM)"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMWB_store"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Store"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMWB_read (SPM)"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMLD (SPM)"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMST (SPM)"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Replacement"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Fwd-GetS"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Fwd-GetM"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Put-Ack"
    cc_state = C_EXA
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC MI^A x Load"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMCP_fetch (coherent)"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMCP_install (SPM)"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMWB_store"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x Store"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMWB_read (SPM)"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMLD (SPM)"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMST (SPM)"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x Replacement"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x Fwd-GetS"
    cc_state = C_MIA
  ==>
  begin
    cc_state := C_SIA;
  endrule;

  rule "CC MI^A x Fwd-GetM"
    cc_state = C_MIA
  ==>
  begin
    cc_state := C_IIA;
  endrule;

  rule "CC MI^A x Put-Ack"
    cc_state = C_MIA
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC EI^A x Load"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMCP_fetch (coherent)"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMCP_install (SPM)"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMWB_store"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x Store"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMWB_read (SPM)"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMLD (SPM)"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMST (SPM)"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x Replacement"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x Fwd-GetS"
    cc_state = C_EIA
  ==>
  begin
    cc_state := C_SIA;
  endrule;

  rule "CC EI^A x Fwd-GetM"
    cc_state = C_EIA
  ==>
  begin
    cc_state := C_IIA;
  endrule;

  rule "CC EI^A x Put-Ack"
    cc_state = C_EIA
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC SI^A x Load"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMCP_fetch (coherent)"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMCP_install (SPM)"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMWB_store"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x Store"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMWB_read (SPM)"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMLD (SPM)"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMST (SPM)"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x Replacement"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x Inv"
    cc_state = C_SIA
  ==>
  begin
    cc_state := C_IIA;
  endrule;

  rule "CC SI^A x Put-Ack"
    cc_state = C_SIA
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC II^A x Load"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMCP_fetch (coherent)"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMCP_install (SPM)"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMWB_store"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x Store"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMWB_read (SPM)"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMLD (SPM)"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMST (SPM)"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x Replacement"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x Put-Ack"
    cc_state = C_IIA
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC IX^D x Load"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMCP_fetch (coherent)"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMCP_install (SPM)"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMWB_store"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Store"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMWB_read (SPM)"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMLD (SPM)"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMST (SPM)"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Replacement"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Exclusive Data 
from Dir"
    cc_state = C_IXD
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC IX^D x Data from Dir
(ack=0)"
    cc_state = C_IXD
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC IX^D x Data from 
Owner"
    cc_state = C_IXD
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC X x SPMWB_store"
    cc_state = C_X
  ==>
  begin
    cc_state := C_XWB;
  endrule;

  rule "CC X x SPMWB_read (SPM)"
    cc_state = C_X
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC X x SPM_release"
    cc_state = C_X
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC X x SPMLD (SPM)"
    cc_state = C_X
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC X x SPMST (SPM)"
    cc_state = C_X
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC XWB x SPMWB_store"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMWB_read (SPM)"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPM_release"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMLD (SPM)"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMST (SPM)"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMWB_Ack"
    cc_state = C_XWB
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "DIR I x SPMWB_Req"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x GetS_silent"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x GetS"
    dir_state = D_I
  ==>
  begin
    dir_state := D_E;
  endrule;

  rule "DIR I x GetM"
    dir_state = D_I
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR I x PutS-NotLast"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x PutS-Last"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x PutM from Non-Owner"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x PutE from Non-Owner"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x GetS_silent"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x GetS"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x GetM"
    dir_state = D_S
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR S x PutS-NotLast"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x PutS-Last"
    dir_state = D_S
  ==>
  begin
    dir_state := D_I;
  endrule;

  rule "DIR S x PutM from Non-Owner"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x PutE from Non-Owner"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x GetS_silent"
    dir_state = D_E
  ==>
  begin
    dir_state := D_SD;
  endrule;

  rule "DIR E x GetS"
    dir_state = D_E
  ==>
  begin
    dir_state := D_SD;
  endrule;

  rule "DIR E x GetM"
    dir_state = D_E
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR E x PutS-NotLast"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x PutS-Last"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x PutM+data from Owner"
    dir_state = D_E
  ==>
  begin
    dir_state := D_I;
  endrule;

  rule "DIR E x PutM from Non-Owner"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x PutE (no-data) from Owner"
    dir_state = D_E
  ==>
  begin
    dir_state := D_I;
  endrule;

  rule "DIR E x PutE from Non-Owner"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x GetS_silent"
    dir_state = D_M
  ==>
  begin
    dir_state := D_SD;
  endrule;

  rule "DIR M x GetS"
    dir_state = D_M
  ==>
  begin
    dir_state := D_SD;
  endrule;

  rule "DIR M x GetM"
    dir_state = D_M
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR M x PutS-NotLast"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x PutS-Last"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x PutM+data from Owner"
    dir_state = D_M
  ==>
  begin
    dir_state := D_I;
  endrule;

  rule "DIR M x PutM from Non-Owner"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x PutE from Non-Owner"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x GetS_silent"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x GetS"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x GetM"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutS-NotLast"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutS-Last"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutM+data from Owner"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutM from Non-Owner"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutE (no-data) from Owner"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutE from Non-Owner"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x Data"
    dir_state = D_SD
  ==>
  begin
    dir_state := D_S;
  endrule;

invariant "CC table state remains declared"
  true;

invariant "Dir table state remains declared"
  true;
