-- Generated by gen_table_model.py. Do not edit by hand.
-- One rule is emitted for each non-empty CSV cell; blank cells have no rule.

type
  CCState: enum {
    C_I, C_ISD, C_IMAD, C_IMA, C_S, C_SXL0, C_SXA, C_SMAD, C_SMA, C_M, C_MXL0, C_MXA, C_E, C_EXL0, C_EXA, C_M_I, C_SINK_WB_ACK, C_MIA, C_EIA, C_SIA, C_IIA, C_IXD, C_X, C_XWB
  };
  DirState: enum {
    D_I, D_S, D_E, D_M, D_SD
  };

var
  cc_state: CCState;
  dir_state: DirState;

startstate "table roots"
begin
  cc_state := C_I;
  dir_state := D_I;
endstartstate;

  rule "CC I x Load"
    cc_state = C_I
  ==>
  begin
    cc_state := C_ISD;
  endrule;

  rule "CC I x SPMCP_fetch"
    cc_state = C_I
  ==>
  begin
    cc_state := C_IXD;
  endrule;

  rule "CC I x SPMCP_install"
    cc_state = C_I
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC I x SPMWB_store"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC I x Store"
    cc_state = C_I
  ==>
  begin
    cc_state := C_IMAD;
  endrule;

  rule "CC I x SPMWB_read"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC I x SPM_release"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC I x SPMLD"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC I x SPMST"
    cc_state = C_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Load"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMCP_fetch"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMCP_install"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMWB_store"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Store"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMWB_read"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPM_release"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMLD"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x SPMST"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Replacement"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Inv"
    cc_state = C_ISD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IS^D x Exclusive Data from Dir"
    cc_state = C_ISD
  ==>
  begin
    cc_state := C_E;
  endrule;

  rule "CC IS^D x Data from Dir (ack=0)"
    cc_state = C_ISD
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC IS^D x Data from Owner"
    cc_state = C_ISD
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC IM^AD x Load"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMCP_fetch"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMCP_install"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMWB_store"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Store"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMWB_read"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPM_release"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMLD"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x SPMST"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Replacement"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Fwd-GetS"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Fwd-GetM"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^AD x Data from Dir (ack=0)"
    cc_state = C_IMAD
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC IM^AD x Data from Dir (ack>0)"
    cc_state = C_IMAD
  ==>
  begin
    cc_state := C_IMA;
  endrule;

  rule "CC IM^AD x Data from Owner"
    cc_state = C_IMAD
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC IM^AD x Inv-Ack"
    cc_state = C_IMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Load"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMCP_fetch"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMCP_install"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMWB_store"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Store"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMWB_read"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPM_release"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMLD"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x SPMST"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Replacement"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Fwd-GetS"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Fwd-GetM"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Inv-Ack"
    cc_state = C_IMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IM^A x Last-Inv-Ack"
    cc_state = C_IMA
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC S x Load"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x SPMCP_fetch"
    cc_state = C_S
  ==>
  begin
    cc_state := C_SXA;
  endrule;

  rule "CC S x SPMCP_install"
    cc_state = C_S
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC S x SPMWB_store"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x Store"
    cc_state = C_S
  ==>
  begin
    cc_state := C_SMAD;
  endrule;

  rule "CC S x SPMWB_read"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x SPM_release"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x SPMLD"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x SPMST"
    cc_state = C_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC S x Replacement"
    cc_state = C_S
  ==>
  begin
    cc_state := C_SIA;
  endrule;

  rule "CC S x Inv"
    cc_state = C_S
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC SX^L0 x Load"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x SPMCP_fetch"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x SPMCP_install"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x SPMWB_store"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x Store"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x SPMWB_read"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x SPM_release"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x SPMLD"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x SPMST"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x Replacement"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x Fwd-GetS"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x Fwd-GetS_Silent"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x Fwd-GetM"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x Inv"
    cc_state = C_SXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^L0 x L0 recall resp"
    cc_state = C_SXL0
  ==>
  begin
    cc_state := C_SXA;
  endrule;

  rule "CC SX^A x Load"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMCP_fetch"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMCP_install"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMWB_store"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Store"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMWB_read"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPM_release"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMLD"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x SPMST"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Replacement"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Fwd-GetS"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Fwd-GetM"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Inv"
    cc_state = C_SXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SX^A x Put-Ack"
    cc_state = C_SXA
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC SM^AD x Load"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMCP_fetch"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMCP_install"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMWB_store"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Store"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMWB_read"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPM_release"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMLD"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x SPMST"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Replacement"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Fwd-GetS"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Fwd-GetM"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^AD x Inv"
    cc_state = C_SMAD
  ==>
  begin
    cc_state := C_IMAD;
  endrule;

  rule "CC SM^AD x Data from Dir (ack=0)"
    cc_state = C_SMAD
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC SM^AD x Data from Dir (ack>0)"
    cc_state = C_SMAD
  ==>
  begin
    cc_state := C_SMA;
  endrule;

  rule "CC SM^AD x Inv-Ack"
    cc_state = C_SMAD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Load"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMCP_fetch"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMCP_install"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMWB_store"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Store"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMWB_read"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPM_release"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMLD"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x SPMST"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Replacement"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Fwd-GetS"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Fwd-GetM"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Inv-Ack"
    cc_state = C_SMA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SM^A x Last-Inv-Ack"
    cc_state = C_SMA
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC M x Load"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPMCP_fetch"
    cc_state = C_M
  ==>
  begin
    cc_state := C_MXA;
  endrule;

  rule "CC M x SPMCP_install"
    cc_state = C_M
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC M x SPMWB_store"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x Store"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPMWB_read"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPM_release"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPMLD"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x SPMST"
    cc_state = C_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M x Replacement"
    cc_state = C_M
  ==>
  begin
    cc_state := C_MIA;
  endrule;

  rule "CC M x Fwd-GetS"
    cc_state = C_M
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC M x Fwd-GetM"
    cc_state = C_M
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC MX^L0 x Load"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x SPMCP_fetch"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x SPMCP_install"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x SPMWB_store"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x Store"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x SPMWB_read"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x SPM_release"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x SPMLD"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x SPMST"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x Replacement"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x Fwd-GetS"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x Fwd-GetS_Silent"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x Fwd-GetM"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x Inv"
    cc_state = C_MXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^L0 x L0 recall resp"
    cc_state = C_MXL0
  ==>
  begin
    cc_state := C_MXA;
  endrule;

  rule "CC MX^A x Load"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMCP_fetch"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMCP_install"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMWB_store"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Store"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMWB_read"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPM_release"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMLD"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x SPMST"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Replacement"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Fwd-GetS"
    cc_state = C_MXA
  ==>
  begin
    cc_state := C_SXA;
  endrule;

  rule "CC MX^A x Fwd-GetS_Silent"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Fwd-GetM"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Inv"
    cc_state = C_MXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MX^A x Put-Ack"
    cc_state = C_MXA
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC E x Load"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x SPMCP_fetch"
    cc_state = C_E
  ==>
  begin
    cc_state := C_EXA;
  endrule;

  rule "CC E x SPMCP_install"
    cc_state = C_E
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC E x SPMWB_store"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x Store"
    cc_state = C_E
  ==>
  begin
    cc_state := C_M;
  endrule;

  rule "CC E x SPMWB_read"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x SPM_release"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x SPMLD"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x SPMST"
    cc_state = C_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC E x Replacement"
    cc_state = C_E
  ==>
  begin
    cc_state := C_EIA;
  endrule;

  rule "CC E x Fwd-GetS"
    cc_state = C_E
  ==>
  begin
    cc_state := C_S;
  endrule;

  rule "CC E x Fwd-GetM"
    cc_state = C_E
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC EX^L0 x Load"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x SPMCP_fetch"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x SPMCP_install"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x SPMWB_store"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x Store"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x SPMWB_read"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x SPM_release"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x SPMLD"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x SPMST"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x Replacement"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x Fwd-GetS"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x Fwd-GetS_Silent"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x Fwd-GetM"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x Inv"
    cc_state = C_EXL0
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^L0 x L0 recall resp"
    cc_state = C_EXL0
  ==>
  begin
    cc_state := C_EXA;
  endrule;

  rule "CC EX^A x Load"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMCP_fetch"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMCP_install"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMWB_store"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Store"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMWB_read"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPM_release"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMLD"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x SPMST"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Replacement"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Fwd-GetS"
    cc_state = C_EXA
  ==>
  begin
    cc_state := C_SXA;
  endrule;

  rule "CC EX^A x Fwd-GetS_Silent"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Fwd-GetM"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Inv"
    cc_state = C_EXA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EX^A x Put-Ack"
    cc_state = C_EXA
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC M_I x Load"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x SPMCP_fetch"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x SPMCP_install"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x SPMWB_store"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x Store"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x SPMWB_read"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x SPM_release"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x SPMLD"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x SPMST"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x WB-Ack"
    cc_state = C_M_I
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC M_I x Replacement"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x Fwd-GetS"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x Fwd-GetS_Silent"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x Fwd-GetM"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC M_I x Inv"
    cc_state = C_M_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x Load"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x SPMCP_fetch"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x SPMCP_install"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x SPMWB_store"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x Store"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x SPMWB_read"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x SPM_release"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x SPMLD"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x SPMST"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x WB-Ack"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC SINK_WB_ACK x Replacement"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x Fwd-GetS"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x Fwd-GetS_Silent"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x Fwd-GetM"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SINK_WB_ACK x Inv"
    cc_state = C_SINK_WB_ACK
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x Load"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMCP_fetch"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMCP_install"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMWB_store"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x Store"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMWB_read"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPM_release"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMLD"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x SPMST"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x Replacement"
    cc_state = C_MIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC MI^A x Fwd-GetS"
    cc_state = C_MIA
  ==>
  begin
    cc_state := C_SIA;
  endrule;

  rule "CC MI^A x Fwd-GetM"
    cc_state = C_MIA
  ==>
  begin
    cc_state := C_IIA;
  endrule;

  rule "CC MI^A x Put-Ack"
    cc_state = C_MIA
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC EI^A x Load"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMCP_fetch"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMCP_install"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMWB_store"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x Store"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMWB_read"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPM_release"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMLD"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x SPMST"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x Replacement"
    cc_state = C_EIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC EI^A x Fwd-GetS"
    cc_state = C_EIA
  ==>
  begin
    cc_state := C_SIA;
  endrule;

  rule "CC EI^A x Fwd-GetM"
    cc_state = C_EIA
  ==>
  begin
    cc_state := C_IIA;
  endrule;

  rule "CC EI^A x Put-Ack"
    cc_state = C_EIA
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC SI^A x Load"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMCP_fetch"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMCP_install"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMWB_store"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x Store"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMWB_read"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPM_release"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMLD"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x SPMST"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x Replacement"
    cc_state = C_SIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC SI^A x Inv"
    cc_state = C_SIA
  ==>
  begin
    cc_state := C_IIA;
  endrule;

  rule "CC SI^A x Put-Ack"
    cc_state = C_SIA
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC II^A x Load"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMCP_fetch"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMCP_install"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMWB_store"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x Store"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMWB_read"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPM_release"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMLD"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x SPMST"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x Replacement"
    cc_state = C_IIA
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC II^A x Put-Ack"
    cc_state = C_IIA
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC IX^D x Load"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMCP_fetch"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMCP_install"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMWB_store"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Store"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMWB_read"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPM_release"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMLD"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x SPMST"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Replacement"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Fwd-GetS"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Fwd-GetS_Silent"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Fwd-GetM"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Inv"
    cc_state = C_IXD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC IX^D x Exclusive Data from Dir"
    cc_state = C_IXD
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC IX^D x Data from Dir (ack=0)"
    cc_state = C_IXD
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC IX^D x Data from Owner"
    cc_state = C_IXD
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC X x SPMWB_store"
    cc_state = C_X
  ==>
  begin
    cc_state := C_XWB;
  endrule;

  rule "CC X x SPMWB_read"
    cc_state = C_X
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC X x SPM_release"
    cc_state = C_X
  ==>
  begin
    cc_state := C_I;
  endrule;

  rule "CC X x SPMLD"
    cc_state = C_X
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC X x SPMST"
    cc_state = C_X
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC X x Replacement"
    cc_state = C_X
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC X x Fwd-GetS"
    cc_state = C_X
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC X x Fwd-GetM"
    cc_state = C_X
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC X x Inv"
    cc_state = C_X
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x Load"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMWB_store"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x Store"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMWB_read"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPM_release"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMLD"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMST"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x SPMWB_Ack"
    cc_state = C_XWB
  ==>
  begin
    cc_state := C_X;
  endrule;

  rule "CC XWB x Replacement"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x Fwd-GetS"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x Fwd-GetS_Silent"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x Fwd-GetM"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "CC XWB x Inv"
    cc_state = C_XWB
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x SPMWB_Req"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x GetS_silent"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x GetS"
    dir_state = D_I
  ==>
  begin
    dir_state := D_E;
  endrule;

  rule "DIR I x GetM"
    dir_state = D_I
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR I x PutS-NotLast"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x PutS-Last"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x PutM from Non-Owner"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR I x PutE from Non-Owner"
    dir_state = D_I
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x SPMWB_Req"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x GetS_silent"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x GetS"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x GetM"
    dir_state = D_S
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR S x PutS-NotLast"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x PutS-Last"
    dir_state = D_S
  ==>
  begin
    dir_state := D_I;
  endrule;

  rule "DIR S x PutM from Non-Owner"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x PutE from Non-Owner"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x SPM_PutS/PutE"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR S x SPM_PutM"
    dir_state = D_S
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x SPMWB_Req"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x GetS_silent"
    dir_state = D_E
  ==>
  begin
    dir_state := D_SD;
  endrule;

  rule "DIR E x GetS"
    dir_state = D_E
  ==>
  begin
    dir_state := D_SD;
  endrule;

  rule "DIR E x GetM"
    dir_state = D_E
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR E x PutS-NotLast"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x PutS-Last"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x PutM+data from Owner"
    dir_state = D_E
  ==>
  begin
    dir_state := D_I;
  endrule;

  rule "DIR E x PutM from Non-Owner"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x PutE (no-data) from Owner"
    dir_state = D_E
  ==>
  begin
    dir_state := D_I;
  endrule;

  rule "DIR E x PutE from Non-Owner"
    dir_state = D_E
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR E x SPM_PutS/PutE"
    dir_state = D_E
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR E x SPM_PutM"
    dir_state = D_E
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR M x SPMWB_Req"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x GetS_silent"
    dir_state = D_M
  ==>
  begin
    dir_state := D_SD;
  endrule;

  rule "DIR M x GetS"
    dir_state = D_M
  ==>
  begin
    dir_state := D_SD;
  endrule;

  rule "DIR M x GetM"
    dir_state = D_M
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR M x PutS-NotLast"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x PutS-Last"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x PutM+data from Owner"
    dir_state = D_M
  ==>
  begin
    dir_state := D_I;
  endrule;

  rule "DIR M x PutM from Non-Owner"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x PutE from Non-Owner"
    dir_state = D_M
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR M x SPM_PutS/PutE"
    dir_state = D_M
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR M x SPM_PutM"
    dir_state = D_M
  ==>
  begin
    dir_state := D_M;
  endrule;

  rule "DIR SD x SPMWB_Req"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x GetS_silent"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x GetS"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x GetM"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutS-NotLast"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutS-Last"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutM+data from Owner"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutM from Non-Owner"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutE (no-data) from Owner"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x PutE from Non-Owner"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x SPM_PutS/PutE"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x SPM_PutM"
    dir_state = D_SD
  ==>
  begin
    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell
  endrule;

  rule "DIR SD x Unblock"
    dir_state = D_SD
  ==>
  begin
    dir_state := D_M;
  endrule;

invariant "CC table state remains declared"
  true;

invariant "Dir table state remains declared"
  true;
