#!/usr/bin/env python3
"""Generate a table-completeness Rumur model from the CacheFlex CSVs."""

from __future__ import annotations

import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CC_CSV = ROOT / "spm_coherency_CC.csv"
DIR_CSV = ROOT / "spm_coherency_dir.csv"
OUT = Path(__file__).resolve().parent / "cacheflex_spm_tables_complete.m"


CC_STATES = [
    "I",
    "IS^D",
    "IM^AD",
    "IM^A",
    "S",
    "SX^A",
    "SM^AD",
    "SM^A",
    "M",
    "MX^A",
    "E",
    "EX^A",
    "MI^A",
    "EI^A",
    "SI^A",
    "II^A",
    "IX^D",
    "X",
    "XWB",
]

DIR_STATES = ["I", "S", "E", "M", "SD"]


def ident(prefix: str, name: str) -> str:
    s = name.strip()
    s = s.replace("^", "")
    s = re.sub(r"[^A-Za-z0-9]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return f"{prefix}_{s}"


def read_table(path: Path, valid_states: list[str]):
    with path.open(newline="") as fh:
        rows = list(csv.reader(fh))
    header = rows[0]
    out = []
    for row in rows[1:]:
        if not row or not row[0].strip():
            break
        state = row[0].strip()
        if state not in valid_states:
            break
        for i, event in enumerate(header[1:], start=1):
            cell = row[i].strip() if i < len(row) else ""
            if cell:
                out.append((state, event.strip(), cell))
    return header[1:], out


def next_state(cell: str, valid_states: list[str]) -> str | None:
    normalized = cell.replace("\n", " ")
    matches = re.findall(r"/\s*([A-Za-z0-9]+(?:\^[A-Za-z0-9]+)?)", normalized)
    if matches:
        candidate = matches[-1]
        if candidate in valid_states:
            return candidate
    return None


def emit_rules(kind: str, state_type: str, var: str, events: list[str], cells):
    lines = []
    states = CC_STATES if kind == "cc" else DIR_STATES
    for state, event, cell in cells:
        dst = next_state(cell, states)
        rule_name = f"{kind.upper()} {state} x {event}"
        lines.append(f'  rule "{rule_name}"')
        lines.append(f"    {var} = {ident(state_type, state)}")
        lines.append("  ==>")
        lines.append("  begin")
        if dst is not None:
            lines.append(f"    {var} := {ident(state_type, dst)};")
        else:
            lines.append("    -- stutter: Hit, Stall, Ignore, Return zero, ack--, or action-only cell")
        lines.append("  endrule;")
        lines.append("")
    return lines


def main() -> None:
    cc_events, cc_cells = read_table(CC_CSV, CC_STATES)
    dir_events, dir_cells = read_table(DIR_CSV, DIR_STATES)

    lines: list[str] = []
    lines.append("-- Generated by gen_table_model.py. Do not edit by hand.")
    lines.append("-- One rule is emitted for each non-empty CSV cell; blank cells have no rule.")
    lines.append("")
    lines.append("type")
    lines.append("  CCState: enum {")
    lines.append("    " + ", ".join(ident("C", s) for s in CC_STATES))
    lines.append("  };")
    lines.append("  DirState: enum {")
    lines.append("    " + ", ".join(ident("D", s) for s in DIR_STATES))
    lines.append("  };")
    lines.append("")
    lines.append("var")
    lines.append("  cc_state: CCState;")
    lines.append("  dir_state: DirState;")
    lines.append("")
    lines.append('startstate "table roots"')
    lines.append("begin")
    lines.append("  cc_state := C_I;")
    lines.append("  dir_state := D_I;")
    lines.append("endstartstate;")
    lines.append("")

    lines.extend(emit_rules("cc", "C", "cc_state", cc_events, cc_cells))
    lines.extend(emit_rules("dir", "D", "dir_state", dir_events, dir_cells))

    lines.append('invariant "CC table state remains declared"')
    lines.append("  true;")
    lines.append("")
    lines.append('invariant "Dir table state remains declared"')
    lines.append("  true;")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")
    print(f"cc non-empty cells: {len(cc_cells)}")
    print(f"dir non-empty cells: {len(dir_cells)}")


if __name__ == "__main__":
    main()
